version: '3'

services:
  devops:
    image: elkingsparx/devops-practice
    container_name: devops-container
    restart: always
    ports:
      - 5173:80
    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

